language: java
sudo: true
dist: trusty
jdk: oraclejdk11

before_install:
  - chmod +x plateforme-cours/mvnw
  - chmod +x plateforme-cours-admin/mvnw
  

deploy:
  provider: heroku
  api_key: $API_KEY_HEROKU
  app: m2-apirest-plateformecours